# Generated by Django 2.2.12 on 2020-06-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cvitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvitem',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
